#!/usr/bin/env python

form netmiko import ConnectHandler

iosv_l2_s1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.72',
    'username': 'artmind',
    'password': 'cisco',
}

iosv_l2_s2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.82',
    'username': 'artmind',
    'password': 'cisco',
}

iosv_l3_r1 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.83',
    'username': 'artmind',
    'password': 'cisco',
}

iosv_l3_r2 = {
    'device_type': 'cisco_ios',
    'ip': '192.168.122.84',
    'username': 'artmind',
    'password': 'cisco',
}

with open('config_file_switches') as f:
    lines = f.read().splitlines()
print (lines)

all_devices = [iosv_l2_s1, iosv_l2_s2]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(lines)
    print (output)


with open('config_file_router') as f:
    lines = f.read().splitlines()
print (lines)

all_devices = [iosv_l3_r1, iosv_l3_r2]

for devices in all_devices:
    net_connect = ConnectHandler(**devices)
    output = net_connect.send_config_set(lines)
    print (output)
